path: C:/BCAExpertise_MiniProjet/porte_avant/data_oriented_boxes
train: C:/BCAExpertise_MiniProjet/porte_avant/data_oriented_boxes/train/images #trainig images : those used to train the model
val: C:/BCAExpertise_MiniProjet/porte_avant/data_oriented_boxes/valid/images #valid images : those used to validate the model performance

# Classes
names:
  0: porte-avant